#!/usr/bin/env python

import rospy
from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint
import math

def generate_circle_points(radius, step_size, duration, num_points):
    points = []
    for i in range(num_points):
        angle = 2 * math.pi * (i / float(num_points))
        x = radius * math.cos(angle)
        y = radius * math.sin(angle)
        point = JointTrajectoryPoint()
        point.positions = [x, y]
        point.time_from_start = rospy.Duration.from_sec((i + 1) * duration)
        points.append(point)
    return points

def main():
    rospy.init_node('head_circle_publisher')
    pub = rospy.Publisher('/head_controller/command', JointTrajectory, queue_size=10)

    radius = 0.5  # Adjust the radius as needed
    step_size = 0.1  # Time between each point
    duration = 0.5  # Duration for each point
    num_points = 20  # Number of points to define the circle

    trajectory = JointTrajectory()
    trajectory.joint_names = ['head_1_joint', 'head_2_joint']
    trajectory.points = generate_circle_points(radius, step_size, duration, num_points)

    rate = rospy.Rate(1 / step_size)  # Publish rate
    while not rospy.is_shutdown():
        trajectory.header.stamp = rospy.Time.now()
        pub.publish(trajectory)
        rate.sleep()

if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        pass
